# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - mv dist _dist
    - go mod tidy
builds:
  - main: ./_dist/apps/goodwin/main.go
    id: goodwin
    binary: goodwin
    goos:
      - darwin
      - linux
      - windows
  - main: ./_dist/apps/voice-cmd/main.go
    id: voice-cmd
    binary: voice-cmd
    goos:
      - darwin
      - linux
      - windows
  - main: ./apps/swagger-proxy/main.go
    id: swagger-proxy
    binary: swagger-proxy
    goos:
      - darwin
      - linux
      - windows
  - main: ./apps/qlab-proxy/main.go
    id: qlab-proxy
    binary: qlab-proxy
    goos:
      - darwin
      - linux
      - windows

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
