# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - main: ./apps/qlab-rest/main.go
    id: goodwin
    binary: goodwin
    goos:
      - darwin
      - linux
      - windows
archives:
  format_overrides:
    - goos: windows
      format: zip
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32_bit
      amd64: 64_bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
