/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberLevelRequest
 */
export interface CueCueNumberLevelRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLevelRequest
     */
    inChannel?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLevelRequest
     */
    outChannel?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLevelRequest
     */
    decibel?: string;
}

export function CueCueNumberLevelRequestFromJSON(json: any): CueCueNumberLevelRequest {
    return CueCueNumberLevelRequestFromJSONTyped(json, false);
}

export function CueCueNumberLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberLevelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inChannel': !exists(json, 'inChannel') ? undefined : json['inChannel'],
        'outChannel': !exists(json, 'outChannel') ? undefined : json['outChannel'],
        'decibel': !exists(json, 'decibel') ? undefined : json['decibel'],
    };
}

export function CueCueNumberLevelRequestToJSON(value?: CueCueNumberLevelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inChannel': value.inChannel,
        'outChannel': value.outChannel,
        'decibel': value.decibel,
    };
}

