/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberGangInChannelOutChannelRequest
 */
export interface CueCueNumberGangInChannelOutChannelRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberGangInChannelOutChannelRequest
     */
    gang?: string;
}

export function CueCueNumberGangInChannelOutChannelRequestFromJSON(json: any): CueCueNumberGangInChannelOutChannelRequest {
    return CueCueNumberGangInChannelOutChannelRequestFromJSONTyped(json, false);
}

export function CueCueNumberGangInChannelOutChannelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberGangInChannelOutChannelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gang': !exists(json, 'gang') ? undefined : json['gang'],
    };
}

export function CueCueNumberGangInChannelOutChannelRequestToJSON(value?: CueCueNumberGangInChannelOutChannelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gang': value.gang,
    };
}

