/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberSliderLevelRequest
 */
export interface CueCueNumberSliderLevelRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberSliderLevelRequest
     */
    channel?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberSliderLevelRequest
     */
    decibel?: string;
}

export function CueCueNumberSliderLevelRequestFromJSON(json: any): CueCueNumberSliderLevelRequest {
    return CueCueNumberSliderLevelRequestFromJSONTyped(json, false);
}

export function CueCueNumberSliderLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberSliderLevelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'decibel': !exists(json, 'decibel') ? undefined : json['decibel'],
    };
}

export function CueCueNumberSliderLevelRequestToJSON(value?: CueCueNumberSliderLevelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel': value.channel,
        'decibel': value.decibel,
    };
}

