/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberSliderLevelChannelRequest
 */
export interface CueCueNumberSliderLevelChannelRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberSliderLevelChannelRequest
     */
    decibel?: string;
}

export function CueCueNumberSliderLevelChannelRequestFromJSON(json: any): CueCueNumberSliderLevelChannelRequest {
    return CueCueNumberSliderLevelChannelRequestFromJSONTyped(json, false);
}

export function CueCueNumberSliderLevelChannelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberSliderLevelChannelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'decibel': !exists(json, 'decibel') ? undefined : json['decibel'],
    };
}

export function CueCueNumberSliderLevelChannelRequestToJSON(value?: CueCueNumberSliderLevelChannelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'decibel': value.decibel,
    };
}

