/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberSecondTriggerActionRequest
 */
export interface CueCueNumberSecondTriggerActionRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberSecondTriggerActionRequest
     */
    number?: string;
}

export function CueCueNumberSecondTriggerActionRequestFromJSON(json: any): CueCueNumberSecondTriggerActionRequest {
    return CueCueNumberSecondTriggerActionRequestFromJSONTyped(json, false);
}

export function CueCueNumberSecondTriggerActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberSecondTriggerActionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function CueCueNumberSecondTriggerActionRequestToJSON(value?: CueCueNumberSecondTriggerActionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
    };
}

