/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberTextFormatAlignmentRequest
 */
export interface CueCueNumberTextFormatAlignmentRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberTextFormatAlignmentRequest
     */
    alignment?: string;
}

export function CueCueNumberTextFormatAlignmentRequestFromJSON(json: any): CueCueNumberTextFormatAlignmentRequest {
    return CueCueNumberTextFormatAlignmentRequestFromJSONTyped(json, false);
}

export function CueCueNumberTextFormatAlignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberTextFormatAlignmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alignment': !exists(json, 'alignment') ? undefined : json['alignment'],
    };
}

export function CueCueNumberTextFormatAlignmentRequestToJSON(value?: CueCueNumberTextFormatAlignmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alignment': value.alignment,
    };
}

