/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberTextFormatFontNameRequest
 */
export interface CueCueNumberTextFormatFontNameRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberTextFormatFontNameRequest
     */
    name?: string;
}

export function CueCueNumberTextFormatFontNameRequestFromJSON(json: any): CueCueNumberTextFormatFontNameRequest {
    return CueCueNumberTextFormatFontNameRequestFromJSONTyped(json, false);
}

export function CueCueNumberTextFormatFontNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberTextFormatFontNameRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CueCueNumberTextFormatFontNameRequestToJSON(value?: CueCueNumberTextFormatFontNameRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

