/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberMoveCartCueChildRequest
 */
export interface CueCueNumberMoveCartCueChildRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberMoveCartCueChildRequest
     */
    row?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberMoveCartCueChildRequest
     */
    column?: string;
}

export function CueCueNumberMoveCartCueChildRequestFromJSON(json: any): CueCueNumberMoveCartCueChildRequest {
    return CueCueNumberMoveCartCueChildRequestFromJSONTyped(json, false);
}

export function CueCueNumberMoveCartCueChildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberMoveCartCueChildRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'row': !exists(json, 'row') ? undefined : json['row'],
        'column': !exists(json, 'column') ? undefined : json['column'],
    };
}

export function CueCueNumberMoveCartCueChildRequestToJSON(value?: CueCueNumberMoveCartCueChildRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'row': value.row,
        'column': value.column,
    };
}

