/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberLiveTranslationRequest
 */
export interface CueCueNumberLiveTranslationRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLiveTranslationRequest
     */
    x?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLiveTranslationRequest
     */
    y?: string;
}

export function CueCueNumberLiveTranslationRequestFromJSON(json: any): CueCueNumberLiveTranslationRequest {
    return CueCueNumberLiveTranslationRequestFromJSONTyped(json, false);
}

export function CueCueNumberLiveTranslationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberLiveTranslationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': !exists(json, 'x') ? undefined : json['x'],
        'y': !exists(json, 'y') ? undefined : json['y'],
    };
}

export function CueCueNumberLiveTranslationRequestToJSON(value?: CueCueNumberLiveTranslationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}

