/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberTextFormatRequest
 */
export interface CueCueNumberTextFormatRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberTextFormatRequest
     */
    jsonString?: string;
}

export function CueCueNumberTextFormatRequestFromJSON(json: any): CueCueNumberTextFormatRequest {
    return CueCueNumberTextFormatRequestFromJSONTyped(json, false);
}

export function CueCueNumberTextFormatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberTextFormatRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonString': !exists(json, 'json_string') ? undefined : json['json_string'],
    };
}

export function CueCueNumberTextFormatRequestToJSON(value?: CueCueNumberTextFormatRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'json_string': value.jsonString,
    };
}

