/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberLiveAverageLevelOutputChannelRequest
 */
export interface CueCueNumberLiveAverageLevelOutputChannelRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLiveAverageLevelOutputChannelRequest
     */
    low?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberLiveAverageLevelOutputChannelRequest
     */
    high?: string;
}

export function CueCueNumberLiveAverageLevelOutputChannelRequestFromJSON(json: any): CueCueNumberLiveAverageLevelOutputChannelRequest {
    return CueCueNumberLiveAverageLevelOutputChannelRequestFromJSONTyped(json, false);
}

export function CueCueNumberLiveAverageLevelOutputChannelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberLiveAverageLevelOutputChannelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'low': !exists(json, 'low') ? undefined : json['low'],
        'high': !exists(json, 'high') ? undefined : json['high'],
    };
}

export function CueCueNumberLiveAverageLevelOutputChannelRequestToJSON(value?: CueCueNumberLiveAverageLevelOutputChannelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'low': value.low,
        'high': value.high,
    };
}

