/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberEffectSetRequest
 */
export interface CueCueNumberEffectSetRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberEffectSetRequest
     */
    parameter?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberEffectSetRequest
     */
    value?: string;
}

export function CueCueNumberEffectSetRequestFromJSON(json: any): CueCueNumberEffectSetRequest {
    return CueCueNumberEffectSetRequestFromJSONTyped(json, false);
}

export function CueCueNumberEffectSetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberEffectSetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameter': !exists(json, 'parameter') ? undefined : json['parameter'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function CueCueNumberEffectSetRequestToJSON(value?: CueCueNumberEffectSetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameter': value.parameter,
        'value': value.value,
    };
}

