/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberFixedWidthRequest
 */
export interface CueCueNumberFixedWidthRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberFixedWidthRequest
     */
    number?: string;
}

export function CueCueNumberFixedWidthRequestFromJSON(json: any): CueCueNumberFixedWidthRequest {
    return CueCueNumberFixedWidthRequestFromJSONTyped(json, false);
}

export function CueCueNumberFixedWidthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberFixedWidthRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function CueCueNumberFixedWidthRequestToJSON(value?: CueCueNumberFixedWidthRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
    };
}

