/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberTextFormatFontFamilyAndStyleRequest
 */
export interface CueCueNumberTextFormatFontFamilyAndStyleRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberTextFormatFontFamilyAndStyleRequest
     */
    family?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberTextFormatFontFamilyAndStyleRequest
     */
    style?: string;
}

export function CueCueNumberTextFormatFontFamilyAndStyleRequestFromJSON(json: any): CueCueNumberTextFormatFontFamilyAndStyleRequest {
    return CueCueNumberTextFormatFontFamilyAndStyleRequestFromJSONTyped(json, false);
}

export function CueCueNumberTextFormatFontFamilyAndStyleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberTextFormatFontFamilyAndStyleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'family': !exists(json, 'family') ? undefined : json['family'],
        'style': !exists(json, 'style') ? undefined : json['style'],
    };
}

export function CueCueNumberTextFormatFontFamilyAndStyleRequestToJSON(value?: CueCueNumberTextFormatFontFamilyAndStyleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'family': value.family,
        'style': value.style,
    };
}

