/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberReplaceLightCommandRequest
 */
export interface CueCueNumberReplaceLightCommandRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberReplaceLightCommandRequest
     */
    oldCommand?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberReplaceLightCommandRequest
     */
    newCommand?: string;
}

export function CueCueNumberReplaceLightCommandRequestFromJSON(json: any): CueCueNumberReplaceLightCommandRequest {
    return CueCueNumberReplaceLightCommandRequestFromJSONTyped(json, false);
}

export function CueCueNumberReplaceLightCommandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberReplaceLightCommandRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oldCommand': !exists(json, 'old_command') ? undefined : json['old_command'],
        'newCommand': !exists(json, 'new_command') ? undefined : json['new_command'],
    };
}

export function CueCueNumberReplaceLightCommandRequestToJSON(value?: CueCueNumberReplaceLightCommandRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'old_command': value.oldCommand,
        'new_command': value.newCommand,
    };
}

