/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberUpdateLightCommandRequest
 */
export interface CueCueNumberUpdateLightCommandRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberUpdateLightCommandRequest
     */
    string?: string;
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberUpdateLightCommandRequest
     */
    number?: string;
}

export function CueCueNumberUpdateLightCommandRequestFromJSON(json: any): CueCueNumberUpdateLightCommandRequest {
    return CueCueNumberUpdateLightCommandRequestFromJSONTyped(json, false);
}

export function CueCueNumberUpdateLightCommandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberUpdateLightCommandRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'string': !exists(json, 'string') ? undefined : json['string'],
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function CueCueNumberUpdateLightCommandRequestToJSON(value?: CueCueNumberUpdateLightCommandRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'string': value.string,
        'number': value.number,
    };
}

