/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberSliceMarkerIndexTimeRequest
 */
export interface CueCueNumberSliceMarkerIndexTimeRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberSliceMarkerIndexTimeRequest
     */
    time?: string;
}

export function CueCueNumberSliceMarkerIndexTimeRequestFromJSON(json: any): CueCueNumberSliceMarkerIndexTimeRequest {
    return CueCueNumberSliceMarkerIndexTimeRequestFromJSONTyped(json, false);
}

export function CueCueNumberSliceMarkerIndexTimeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberSliceMarkerIndexTimeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': !exists(json, 'time') ? undefined : json['time'],
    };
}

export function CueCueNumberSliceMarkerIndexTimeRequestToJSON(value?: CueCueNumberSliceMarkerIndexTimeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
    };
}

