/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CueCueNumberTextFormatUnderlineStyleRequest
 */
export interface CueCueNumberTextFormatUnderlineStyleRequest {
    /**
     * 
     * @type {string}
     * @memberof CueCueNumberTextFormatUnderlineStyleRequest
     */
    style?: string;
}

export function CueCueNumberTextFormatUnderlineStyleRequestFromJSON(json: any): CueCueNumberTextFormatUnderlineStyleRequest {
    return CueCueNumberTextFormatUnderlineStyleRequestFromJSONTyped(json, false);
}

export function CueCueNumberTextFormatUnderlineStyleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CueCueNumberTextFormatUnderlineStyleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'style': !exists(json, 'style') ? undefined : json['style'],
    };
}

export function CueCueNumberTextFormatUnderlineStyleRequestToJSON(value?: CueCueNumberTextFormatUnderlineStyleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'style': value.style,
    };
}

