/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplyFormatRequest
 */
export interface ReplyFormatRequest {
    /**
     * 
     * @type {string}
     * @memberof ReplyFormatRequest
     */
    formatString?: string;
}

export function ReplyFormatRequestFromJSON(json: any): ReplyFormatRequest {
    return ReplyFormatRequestFromJSONTyped(json, false);
}

export function ReplyFormatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplyFormatRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formatString': !exists(json, 'format_string') ? undefined : json['format_string'],
    };
}

export function ReplyFormatRequestToJSON(value?: ReplyFormatRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'format_string': value.formatString,
    };
}

