/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequest
 */
export interface SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequest {
    /**
     * 
     * @type {string}
     * @memberof SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequest
     */
    location?: string;
}

export function SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequestFromJSON(json: any): SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequest {
    return SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequestFromJSONTyped(json, false);
}

export function SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequestToJSON(value?: SettingsVideoSurfacesSurfaceIDScreenIndexOriginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': value.location,
    };
}

