/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WorkspacesCue,
    WorkspacesCueFromJSON,
    WorkspacesCueFromJSONTyped,
    WorkspacesCueToJSON,
} from './WorkspacesCue';

/**
 * response object for /workspace/{id}/cueLists
 * @export
 * @interface WorkspaceIdCueListsResponse
 */
export interface WorkspaceIdCueListsResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceIdCueListsResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceIdCueListsResponse
     */
    address?: string;
    /**
     * 
     * @type {Array<WorkspacesCue>}
     * @memberof WorkspaceIdCueListsResponse
     */
    data?: Array<WorkspacesCue>;
}

export function WorkspaceIdCueListsResponseFromJSON(json: any): WorkspaceIdCueListsResponse {
    return WorkspaceIdCueListsResponseFromJSONTyped(json, false);
}

export function WorkspaceIdCueListsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceIdCueListsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(WorkspacesCueFromJSON)),
    };
}

export function WorkspaceIdCueListsResponseToJSON(value?: WorkspaceIdCueListsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'address': value.address,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(WorkspacesCueToJSON)),
    };
}

