/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspacesResponseData
 */
export interface WorkspacesResponseData {
    /**
     * 
     * @type {string}
     * @memberof WorkspacesResponseData
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspacesResponseData
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspacesResponseData
     */
    uniqueID?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspacesResponseData
     */
    hasPasscode?: boolean;
}

export function WorkspacesResponseDataFromJSON(json: any): WorkspacesResponseData {
    return WorkspacesResponseDataFromJSONTyped(json, false);
}

export function WorkspacesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspacesResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'uniqueID': !exists(json, 'uniqueID') ? undefined : json['uniqueID'],
        'hasPasscode': !exists(json, 'hasPasscode') ? undefined : json['hasPasscode'],
    };
}

export function WorkspacesResponseDataToJSON(value?: WorkspacesResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'displayName': value.displayName,
        'uniqueID': value.uniqueID,
        'hasPasscode': value.hasPasscode,
    };
}

