/* tslint:disable */
/* eslint-disable */
/**
 * QLab OSC Rest Proxy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceIdRenumberRequest
 */
export interface WorkspaceIdRenumberRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceIdRenumberRequest
     */
    startNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceIdRenumberRequest
     */
    incrementNumber?: string;
}

export function WorkspaceIdRenumberRequestFromJSON(json: any): WorkspaceIdRenumberRequest {
    return WorkspaceIdRenumberRequestFromJSONTyped(json, false);
}

export function WorkspaceIdRenumberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceIdRenumberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startNumber': !exists(json, 'startNumber') ? undefined : json['startNumber'],
        'incrementNumber': !exists(json, 'incrementNumber') ? undefined : json['incrementNumber'],
    };
}

export function WorkspaceIdRenumberRequestToJSON(value?: WorkspaceIdRenumberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startNumber': value.startNumber,
        'incrementNumber': value.incrementNumber,
    };
}

